### ISSUE TITLE
DCMIL Website

### ISSUE THREAD

**Issue by JayLuke780** [JayLuke780/ProjectAllen#2]
User Story:
As a Developer, I would like to research the DC Metro Immigration web site for services rendered
so that I can get a better of understanding of what requirements we need for automating their processes.

Acceptance Criteria:
1) Go to http://www.dcmil.com
2) Analyze and annotate the content within the web site for services and functionality
3) Review structure of website and layout for possible improvements and annotate findings.

Story Points : 2

**Comment by tyonas9** [comment]
Overview of DCMIL
Immigration law company : provides immigration legal services 
Services includes :
                   - Change / extension of status
                   - Citizenship and Naturalization
                   - Differed Action ( dreamers)
                   - Employment Immigration
                   - Family Immigration
                   - H1B Visas 2015
                   - Removal Proceedings ( immigration court)
                   - Special Circumstances
                   - Student Immigration
How : 
Via a web based ( SaaS platform ) case management system called ‘My Case' and also a legacy system called ( eimmigration)

i.e. Case management system with client access via email. Upload and view documents for your case, securely message the attorney and staff, and see and receive reminders on your own calendar.

 User ( customer )  -> contact dcmil ( seek service) 
                              - > Upload the necessary documents on ‘mycase'
                              - > View processed document
                              - > Can securely message staff and attorney
                              - > Receive reminders about the processed case on calendar

DCMIL( company ) - > Contact customer
                               - > Receive documents to process 
                               - > Process the files ( provide legal service )
                               - > Upload the processed files to be accessed by the customer 

Recommendation:
- Current dcmil website could be revamped with a clean design 
- Custom Case management system could also be in-house developed so as to  cut monthly subscription fees
- Can create a data warehouse for service provisions and leverage it for analysis and reporting purposes

**Comment by tyonas9** [comment]
Hello Team,


Jay:
I went through the DCMIL website and also talked to Amy this morning to try
to grasp the processes. I've put the overview and the recommendations on
github. Please go through it and send me your feedbacks. In the mean time
Amy will bring the forms and any related documents the company uses so as
to cement our understanding when we architect the whole scenario on the
white board over the weekend.

Cheers.

**Comment by JayLuke780** [comment]
Excellent, exactly what I was looking for.  That's enough for us to discuss
this weekend for the scrum.

Amy feel free to share your ideas or wish list on how to better improve
your day to day task.

-Jay

**Comment by tyonas9** [comment]
Hey Team,

That's great Jay. Can't wait to nail it. I've a feeling it's going to be
fun and will also create a plethora of ways to learn all the tools and ways
to manipulate and make use of large data.
One more quick update. I've installed all the power query, power pivot and
power BI on Amy's machine.

Amy:
All these softwares ( Power Query, Power Pivot and Power BI ) help us
leverage the data and be able to create all the analysis and reporting
directly on excel instead of using the Visual studio to develop the reports
and do analysis. Imagine it like, creating visually appealing reports using
your data that for instance has 15 million lines of data on excel. Anyhow,
I'm just trying to say how it's easy and fun to play with.

Thanks.

**Comment by JayLuke780** [comment]
Awesome Jonas. I like the attitude and I'm excited as well to use this
project as a platform for all our skills. You know the old saying "iron
sharpens iron" , so continue to assist Amy in her familiarity of IT,
software, and hardware.

The key here will be whatever you learn you have to be able to explain it
to a 5 year old. Teach it to someone who doesn't have a clue, this way it
helps you with explaining what you did on interviews and makes sure your
confident because you have to know it well to teach it.

Like I said before, we will be starting small to get the foundation ready,
but then we'll start branching out to specific concentrations (BI,
sharepoint, bigdata, , ux, ect) each of us picking a role for the time
being then switching with still assisting each other. Looking forward to
seeing you tomorrow guys.

-Jay
